spring.application.name=ce

server.port=5055

server.error.whitelabel.enabled=false

spring.security.oauth2.client.registration.github.client-id=client_id
spring.security.oauth2.client.registration.github.client-secret=client_secret

spring.security.oauth2.client.registration.github.scope=read:user,repo,read:org

